development:
  sessions:
    default:
      database: load_test #cipci_v3 #pophealth-development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: pophealth-test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: cipci_v3 #pophealth-production
      hosts:
        - localhost:27017
